#ifndef VERSION_H
#define VERSION_H

#define DEFF_VER_MAJOR      0
#define DEFF_VER_MINOR      0
#define DEFF_VER_REVISION   3
#define DEFF_VER_SUBREV     0

#ifndef ETOSTRING
#define ASSTRING(e)     #e
#define ETOSTRING(e)    ASSTRING(e)
#endif

#define DEFF_VERSION_LONG   ("" ETOSTRING( DEFF_VER_MAJOR ) "." ETOSTRING( DEFF_VER_MINOR ) "." ETOSTRING( DEFF_VER_REVISION ) "." ETOSTRING( DEFF_VER_SUBREV ) "")
#define DEFF_VERSION_SHORT  ("" ETOSTRING( DEFF_VER_MAJOR ) "." ETOSTRING( DEFF_VER_MINOR ) "." ETOSTRING( DEFF_VER_REVISION ) "")

#endif /* VERSION_H */
